// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvCGPTd-E1NvsJDfpXgdrZ8KZhdd0n4vo',
    appId: '1:846013768914:web:0ec1a8ab76f2a3f014b90b',
    messagingSenderId: '846013768914',
    projectId: 'chatapptute-2b493',
    authDomain: 'chatapptute-2b493.firebaseapp.com',
    storageBucket: 'chatapptute-2b493.appspot.com',
    measurementId: 'G-36G39YST22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAESbUP2_nh3BYqe8Rss0NjfA4KD3_ehVg',
    appId: '1:846013768914:android:3b81fdc558c8106314b90b',
    messagingSenderId: '846013768914',
    projectId: 'chatapptute-2b493',
    storageBucket: 'chatapptute-2b493.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKaLH4hdckcrgHUsE-Ih8wS7R64kE9DdM',
    appId: '1:846013768914:ios:8b1a20fd0e053b6714b90b',
    messagingSenderId: '846013768914',
    projectId: 'chatapptute-2b493',
    storageBucket: 'chatapptute-2b493.appspot.com',
    iosBundleId: 'com.example.appchatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKaLH4hdckcrgHUsE-Ih8wS7R64kE9DdM',
    appId: '1:846013768914:ios:8b1a20fd0e053b6714b90b',
    messagingSenderId: '846013768914',
    projectId: 'chatapptute-2b493',
    storageBucket: 'chatapptute-2b493.appspot.com',
    iosBundleId: 'com.example.appchatFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvCGPTd-E1NvsJDfpXgdrZ8KZhdd0n4vo',
    appId: '1:846013768914:web:f7eed18f6bac446f14b90b',
    messagingSenderId: '846013768914',
    projectId: 'chatapptute-2b493',
    authDomain: 'chatapptute-2b493.firebaseapp.com',
    storageBucket: 'chatapptute-2b493.appspot.com',
    measurementId: 'G-Z0S70E4CSW',
  );
}
